"""empty message

Revision ID: 34b7c255d5da
Revises: 
Create Date: 2023-06-06 10:17:38.873104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b7c255d5da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('choose_flag', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exclude',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exclude_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_flag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_flag', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workplace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email_address', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=100), nullable=True),
    sa.Column('hide_flag', sa.Boolean(), nullable=False),
    sa.Column('workplace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workplace_id'], ['workplace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bento_id', sa.Integer(), nullable=False),
    sa.Column('reservation_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['bento_id'], ['bento.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    op.drop_table('user')
    op.drop_table('workplace')
    op.drop_table('time_flag')
    op.drop_table('exclude')
    op.drop_table('bento')
    # ### end Alembic commands ###
